geoserver/geoserver-acl

- src/domain/rule-management/src/test/java/org/geoserver/acl/domain/rules/RuleAdminServiceIT.java
- src/integration/openapi/java-client/src/main/java/org/geoserver/acl/api/client/integration/RuleRepositoryClientAdaptor.java
- src/integration/openapi/spring-server/src/main/java/org/geoserver/acl/api/server/rules/RulesApiImpl.java
- src/integration/persistence-jpa/integration/src/main/java/org/geoserver/acl/integration/jpa/repository/RuleRepositoryJpaAdaptor.java
- src/integration/persistence-jpa/model/src/main/java/org/geoserver/acl/jpa/repository/JpaRuleRepository.java
`@ElementCollection` delete is not cascaded outside the entitymanager (i.e. if delete is performed by an `@Query`)
> Fix error deleting rules with layer attributes

- src/domain/rule-management/src/test/java/org/geoserver/acl/domain/rules/RuleAdminServiceIT.java
- src/integration/persistence-jpa/integration/src/test/java/org/geoserver/acl/integration/jpa/it/RuleRepositoryJpaAdaptorTest.java
- src/integration/persistence-jpa/model/src/main/java/org/geoserver/acl/jpa/model/LayerDetails.java
Using LOB may prevent loading Rules without a transaction
> Don't use CLOB column type for JPA's LayerDetails cql filters

- pom.xml
- src/artifacts/api/pom.xml
- src/integration/openapi/java-client/pom.xml
- src/integration/openapi/java-e2e/pom.xml
- src/integration/openapi/model-mapping/pom.xml
- src/integration/openapi/pom.xml
- src/integration/openapi/spring-server/pom.xml
- src/integration/spring-boot/spring-boot-simplejndi/pom.xml
- src/plugin/client/pom.xml
- src/pom.xml
Upgrade to spring-boot 2.7.10/snakeyaml 2.0
It only affects the api service, the geoserver plugin
does not carry over the snakeyaml dependency nor any
spring-boot one.
> Upgrade to spring-boot 2.7.10/snakeyaml 2.0

- src/artifacts/plugin/pom.xml
- src/artifacts/plugin/src/main/java/org/geoserver/acl/plugin/autoconfigure/accessmanager/AclAccessManagerAutoConfiguration.java
- src/artifacts/plugin/src/main/java/org/geoserver/acl/plugin/autoconfigure/accessmanager/ConditionalOnAclEnabled.java
- src/artifacts/plugin/src/main/java/org/geoserver/acl/plugin/autoconfigure/webui/AclWebUIAutoConfiguration.java
- src/artifacts/plugin/src/main/java/org/geoserver/acl/plugin/autoconfigure/wps/AclWpsAutoConfiguration.java
- src/artifacts/plugin/src/main/resources/META-INF/spring.factories
- src/integration/openapi/java-client/pom.xml
- src/integration/openapi/java-client/src/main/java/org/geoserver/acl/api/client/integration/AuthorizationServiceClientAdaptor.java
- src/openapi/java-client/pom.xml
- src/plugin/client/pom.xml
- src/pom.xml
Provide plugin autoconfigurations for spring-boot
If the plugin is run in a spring-boot application, the autoconfigurations will set up the application context contributions from the plugin modules `@Configuration` classes.
If run on vanilla GeoServer, the usual `applicationContext.xml` files will load the `@Configuration` classes instead.
> Spring Boot integration for the GeoServer plugin

- src/artifacts/api/pom.xml
- src/artifacts/api/src/main/java/org/geoserver/acl/app/AccesControlListApplication.java
- src/artifacts/api/src/main/java/org/geoserver/acl/generateddl/GenerateDDL.java
- src/artifacts/api/src/main/resources/acl-service.yml
- src/artifacts/api/src/main/resources/application.yml
- src/integration/persistence-jpa/integration/src/test/resources/application-test.yaml
- src/integration/persistence-jpa/model/src/main/java/org/geoserver/acl/jpa/model/AdminRule.java
- src/integration/persistence-jpa/model/src/main/java/org/geoserver/acl/jpa/model/Rule.java
- src/integration/persistence-jpa/model/src/test/java/org/geoserver/acl/jpa/it/JpaAdminRuleRepositoryPostGIS_IT.java
- src/integration/persistence-jpa/model/src/test/java/org/geoserver/acl/jpa/it/JpaRuleRepositoryPostGIS_IT.java
- src/integration/persistence-jpa/model/src/test/resources/application-test.yaml
* Not specifying the hibernate-spatial dialect to use results in geometry columns of type `bytea` instead of `geometry`.
* Create a sequence for each entity (`acl_rule_sequence` and `acl_adminrule_sequence`) instead of all using the default `hibernate_sequence`.
* Add a `generateddl` application argument to write the db schema DDL to stdout and exit. Run with, for example:
```
docker-compose run --rm acl generateddl
```
> Set hibernate-spatial dialect and use a sequence per entity

- src/artifacts/api/Dockerfile
- src/artifacts/api/src/main/java/org/geoserver/acl/autoconfigure/security/AclServiceSecurityAutoConfiguration.java
The actuator is at `/acl/actuator`.
Only `/acl/actuator/health/**` is public, any
other endpoint requires a `ROLE_ADMIN`.
> Secure the actuator and fix healthcheck

- .github/workflows/build.yaml
- Makefile
- examples/java-client/pom.xml
- examples/java-client/src/test/java/org/geoserver/acl/examples/javaclient/JavaClientAdaptorExampleTest.java
- examples/java-client/src/test/resources/logback-test.xml
- examples/pom.xml
- src/integration/openapi/java-client/src/main/java/org/geoserver/acl/client/AclClient.java
Create an examples project that demonstrates
how to use the API Client with the adaptor
to use the domain services and authorization
API with repository implementations backed
by the OpenAPI client.
> Add API client usage example

- pom.xml
Fetching spring dependencies from repo.spring.io
is discouraged and giving an auth error now.
They should be grabbed from the central maven repo.
> Remove repo.spring.io maven repository

- src/plugin/web/pom.xml
GeoSever fixed the mockito-core dependency scope from compile to test. Add the required dependency for the web plugin to build.
> Fix plugin build against gs:2.24.x

- src/artifacts/plugin/src/test/java/org/geoserver/acl/plugin/autoconfigure/accessmanager/AclAccessManagerAutoConfigurationTest.java
- src/plugin/accessmanager/src/main/java/org/geoserver/acl/plugin/accessmanager/ACLDispatcherCallback.java
- src/plugin/accessmanager/src/main/java/org/geoserver/acl/plugin/accessmanager/ACLResourceAccessManager.java
- src/plugin/accessmanager/src/main/java/org/geoserver/acl/plugin/config/accessmanager/AccessManagerSpringConfig.java
Make sure ACLAccessManager uses the application context provided LayerGroupContainmentCache.
> plugin: access manager use provided LayerGroupContainmentCache

- pom.xml
- src/artifacts/api/pom.xml
- src/integration/openapi/java-client-spring6/pom.xml
- src/integration/openapi/java-client/pom.xml
- src/integration/openapi/model-mapping/pom.xml
- src/integration/persistence-jpa/integration/pom.xml
- src/integration/persistence-jpa/model/pom.xml
- src/openapi/spring5/java-client/pom.xml
- src/openapi/spring5/model/pom.xml
- src/openapi/spring5/server-api/pom.xml
- src/openapi/spring6/java-client/pom.xml
- src/openapi/spring6/model/pom.xml
- src/plugin/client/pom.xml
- src/plugin/plugin/pom.xml
- src/pom.xml
Maven plugin versions upgrade
```    
com.github.ekryd.sortpom:sortpom-maven-plugin ..... 2.13.1 -> 3.3.0
io.github.git-commit-id:git-commit-id-maven-plugin . 5.0.0 -> 7.0.0
maven-enforcer-plugin .............................. 3.0.0 -> 3.4.1
maven-failsafe-plugin .............................. 3.0.0 -> 3.2.1
maven-resources-plugin ............................. 3.3.0 -> 3.3.1
maven-source-plugin ................................ 3.2.1 -> 3.3.0
maven-surefire-plugin .............................. 3.0.0 -> 3.2.1
org.codehaus.mojo:build-helper-maven-plugin ........ 3.3.0 -> 3.4.0
org.codehaus.mojo:flatten-maven-plugin ............. 1.2.2 -> 1.5.0
org.openapitools:openapi-generator-maven-plugin .... 7.0.0 -> 7.0.1
```
> Maven plugin versions upgrade

- src/plugin/plugin/src/main/java/org/geoserver/acl/plugin/autoconfigure/webui/AclWebUIAutoConfiguration.java
- src/plugin/plugin/src/test/java/org/geoserver/acl/plugin/autoconfigure/webui/AclWebUIAutoConfigurationTest.java
Expecting the `securityCategory` to be present in the application context does not work as it may not have yet been loaded, and we can't reference a GeoServer Cloud autoconfiguration class from this project to run `AclWebUIAutoConfiguration` after it.
> Disable web-ui by default, require config property goserver.web-ui.acl.enabled=true

- src/openapi/spring5/pom.xml
- src/openapi/spring6/pom.xml
- src/plugin/accessmanager/pom.xml
- src/plugin/config/pom.xml
- src/plugin/pom.xml
- src/plugin/web/pom.xml
- src/plugin/wps/pom.xml
- src/pom.xml
* org.jsoup:jsoup:1.16.2 -> 1.17.1
* io.swagger.core.v3:swagger-annotations:2.2.18 -> 2.2.19
* spring-boot.version:2.7.15 -> 2.7.18
* spring-boot-3.version:3.0.10 -> 3.0.13
* lombok.version:1.18.26 -> 1.18.30
* caffeine.version:3.1.2 -> 3.1.8
* flyway.version:8.5.13 -> 9.22.3
> Dependency upgrades to latest releases

- README.md
Java 17 is actually needed, the build fails under JDK11.
The version has been enforced following ea2cf948.
> fix README regarding Java version compatibility

- compose-acl-config.yml
- compose.yml
- docs/management.md
- src/artifacts/api/Dockerfile
- src/artifacts/api/src/main/resources/application.yml
- src/artifacts/testcontainer/src/main/java/org/geoserver/acl/testcontainer/GeoServerAclContainer.java
For security reasons, use a different port for spring boot actuator endpoints than the application's port.
> Change management port to 8081

- src/plugin/web/src/main/java/org/geoserver/acl/plugin/web/accessrules/model/MutableAccessRequest.java
- src/plugin/web/src/main/java/org/geoserver/acl/plugin/web/accessrules/model/MutableLayerDetails.java
Fix mutability of collection properties in `MutableAccessRequest` and `MutableLayerDetails` broken in commit
7883f704c01f4186c8adaac142dcca273f8513ac
"Replace Stream.collect(Collectors.toList()) by Stream.toList()"
> plugin: fix webui model's mutability of collection properties

- examples/java-client/pom.xml
- examples/pom.xml
- src/artifacts/api/src/main/java/org/geoserver/acl/autoconfigure/security/InternalSecurityAutoConfiguration.java
- src/artifacts/api/src/main/resources/META-INF/spring.factories
- src/artifacts/api/src/main/resources/application.yml
- src/artifacts/api/src/main/resources/values.yml
- src/artifacts/api/src/test/java/org/geoserver/acl/autoconfigure/security/InternalSecurityAutoConfigurationTest.java
In production systems the internal user passwords are to be defined in (k8s/docker) secrets.
Allowing to use plain text passwords is not a problem in that case and enables sharing the secrets across the ACL service configuration and the GeoServer plugin clients.
> Allow defining internal users with plaintext passwords

- .github/workflows/build-plugin.yaml
- Makefile
- src/plugin/pom.xml
Test the plugin against the following GeoServer versions:
* dev: `2.26-SNAPSHOT`
* stable: `2.25.0`
* maintenance: `2.24.2`
> Update the GeoSever versions the plugin is tested against

- src/artifacts/api/pom.xml
- src/artifacts/api/src/main/resources/application.yml
- src/artifacts/api/src/test/java/org/geoserver/acl/app/AbstractAccesControlListApplicationTest.java
- src/artifacts/api/src/test/java/org/geoserver/acl/app/AccesControlListApplicationIT.java
- src/artifacts/api/src/test/java/org/geoserver/acl/app/AccesControlListApplicationTest.java
- src/integration/openapi/spring-server/src/main/java/org/geoserver/acl/api/server/support/ApiImplSupport.java
- src/integration/openapi/spring-server/src/test/java/org/geoserver/acl/api/server/rules/RulesApiImpTest.java
- src/integration/persistence-jpa/model/src/test/java/org/geoserver/acl/jpa/it/JpaAdminRuleRepositoryPostGIS_IT.java
- src/integration/persistence-jpa/model/src/test/java/org/geoserver/acl/jpa/it/JpaRuleRepositoryPostGIS_IT.java
- src/pom.xml
Flyway 10.x switched to a modular dependency approach. Now it's required to add a dependency on `flyway-database-postgresql`
> Add dependency on flyway-database-postgresql after flyway 10.x upgrade

- compose/compose.yml
- compose/gateway-service.yml
- src/artifacts/api/pom.xml
- src/artifacts/api/src/main/java/org/geoserver/acl/autoconfigure/springdoc/SpringDocAutoConfiguration.java
- src/artifacts/api/src/main/java/org/geoserver/acl/autoconfigure/springdoc/SpringDocHomeRedirectController.java
- src/artifacts/api/src/main/resources/application.yml
- src/artifacts/api/src/test/java/org/geoserver/acl/app/AbstractAccesControlListApplicationTest.java
- src/artifacts/api/src/test/java/org/geoserver/acl/app/AccesControlListApplicationTest.java
In order for the swagger ui to automatically respect the `X-Forwarded-Prefix` header, the config property
`server.forward-headers-strategy` must be `framework` when using Tomcat.
Additionally, the spring-doc swagger-ui won't respect the servlet context path (i.e. `/acl`) when building URLs and the `X-Forwarded-Prefix` is received (and handled by
`org.springframework.web.filter.ForwardedHeaderFilter` as result of `server.forward-headers-strategy=framework`.
This patch handles the servlet context suffixing at `SpringDocHomeRedirectController` and `SpringDocAutoConfiguration`.
> Fix handling of forwarded headers and servlet context path for swagger ui

- src/artifacts/api/pom.xml
- src/artifacts/api/src/main/java/org/geoserver/acl/autoconfigure/cache/CachingAuthorizationServiceServerAutoConfiguration.java
- src/artifacts/api/src/main/resources/META-INF/spring.factories
- src/artifacts/api/src/main/resources/application.yml
- src/artifacts/api/src/main/resources/values.yml
- src/plugin/accessmanager/src/main/java/org/geoserver/acl/plugin/accessmanager/ACLResourceAccessManager.java
- src/plugin/plugin/src/main/java/org/geoserver/acl/plugin/autoconfigure/cache/CachingAuthorizationServicePluginAutoConfiguration.java
- src/plugin/plugin/src/main/resources/META-INF/spring.factories
Support `AuthorizationService` caching decorator on the server, the same way as done in the client.
Enabled automatically through the config property
`geoserver.acl.caching.enabled` and the shorter property name in `values.yml` named `acl.caching` (as usual to ease overriding through env variables).
> Add server-side authorization requests caching

- src/artifacts/api/src/main/java/org/geoserver/acl/autoconfigure/security/AuthenticationManagerAutoConfiguration.java
- src/artifacts/api/src/main/java/org/geoserver/acl/autoconfigure/security/PreAuthenticationSecurityAutoConfiguration.java
- src/artifacts/api/src/main/resources/values.yml
- src/artifacts/api/src/test/java/org/geoserver/acl/app/AccesControlListApplicationTest.java
- src/artifacts/api/src/test/java/org/geoserver/acl/autoconfigure/security/PreAuthenticationSecurityAutoConfigurationTest.java
`values.yml` had wrongly defined the value for the `acl.security.headers.admin-roles` property.
Fix it and add tests.
> Fix config of default admin role names for http headers preauthentication

- src/pom.xml
Fixes the plugin build for the gs-dev maven profile
> Upgrade spring and spring-security versions to match GeoServer 2.6-SNAPSHOT ones

- src/application/authorization-api/src/main/java/org/geoserver/acl/authorization/AccessSummary.java
- src/application/authorization-api/src/main/java/org/geoserver/acl/authorization/WorkspaceAccessSummary.java
- src/plugin/accessmanager/src/main/java/org/geoserver/acl/plugin/accessmanager/CatalogSecurityFilterBuilder.java
- src/plugin/accessmanager/src/test/java/org/geoserver/acl/plugin/accessmanager/CatalogSecurityFilterBuilderTest.java
Increase test coverage for `CatalogSecurityFilterBuilder` to 98.3% and fix bugs found when rules produce `AccessSummary`s with a mixture allow all or deny all workspaces, and concrete workspaces.
@see 52d455505b25a4d98296027d8debf89ae9818e20
> Bug fixes in building ResourceAccessManager's securityFilter

- .github/workflows/build-and-push-image.yaml
Build the ACL API service docker image for`linux/amd64` and `linux/arm64` platforms
> Build multiplatform docker image for the API service

- pom.xml
Upgrade dependency convergence enforced versions to match the latest GeoServer 2.27.x main branch:
* Upgrade commons-lang from 2.5 to 2.6
* Upgrade guava from 33.2.1 to 33.4.0
* Upgrade commons-io from 2.16.1 to 2.18.0
* Upgrade Wicket from 9.19.0 to 9.20.0
> Geoserver dependency upgrades

- pom.xml
- src/artifacts/api/src/test/java/org/geoserver/acl/app/AccesControlListApplicationIT.java
- src/domain/adminrule-management/src/main/java/org/geoserver/acl/domain/adminrules/AdminRuleAdminServiceImpl.java
- src/domain/rule-management/src/main/java/org/geoserver/acl/domain/rules/RuleAdminServiceImpl.java
- src/integration/persistence-jpa/integration/src/main/java/org/geoserver/acl/integration/jpa/repository/PriorityResolver.java
- src/integration/persistence-jpa/integration/src/main/java/org/geoserver/acl/integration/jpa/repository/RuleRepositoryJpaAdaptor.java
- src/integration/persistence-jpa/integration/src/test/java/org/geoserver/acl/integration/jpa/it/AdminRuleRepositoryJpaAdaptorTest.java
- src/integration/persistence-jpa/integration/src/test/java/org/geoserver/acl/integration/jpa/it/AuthorizationServiceImplAccessSummaryJpaIT.java
- src/integration/persistence-jpa/integration/src/test/java/org/geoserver/acl/integration/jpa/it/AuthorizationServiceImplJpaGeomIT.java
- src/integration/persistence-jpa/integration/src/test/java/org/geoserver/acl/integration/jpa/it/AuthorizationServiceImplJpaIT.java
- src/integration/persistence-jpa/integration/src/test/java/org/geoserver/acl/integration/jpa/it/RuleAdminServiceJpaIT.java
- src/integration/persistence-jpa/integration/src/test/java/org/geoserver/acl/integration/jpa/it/RuleRepositoryJpaAdaptorTest.java
- src/integration/persistence-jpa/model/src/main/java/org/geoserver/acl/jpa/config/AuthorizationJPAConfiguration.java
- src/integration/persistence-jpa/model/src/test/java/org/geoserver/acl/jpa/it/JpaAdminRuleRepositoryPostGIS_IT.java
- src/integration/persistence-jpa/model/src/test/java/org/geoserver/acl/jpa/it/JpaRuleRepositoryPostGIS_IT.java
Multiple threads creating rules with the same priority concurrently resulted in duplicate priorities instead of consecutive values. The priority resolution logic (check if priority exists → shift existing rules → insert new rule) was not atomic, allowing race conditions.
Solution:
Added ReentrantLock to serialize all priority-mutating operations (insert, update, shift, swap) in both RuleAdminServiceImpl and AdminRuleAdminServiceImpl. The write lock is acquired BEFORE the transaction starts, ensuring the entire check-shift-insert operation is serialized at the application level.
Why application-level locking:
- Pessimistic database locks: Don't prevent phantom reads when checking for non-existent priorities. Row-level locks only work on existing rows.
- PostgreSQL advisory locks: Require …
> Fix race condition in concurrent rule creation with same priority
